const express = require("express");
const router = express.Router();
const {register,logon,logoff,googleLogon,}=require("../controllers/userController");
const jwtMiddleware = require("../middleware/jwtMiddleware");
router.route("/register").post(register);
router.route("/logon").post(logon);
router.use(jwtMiddleware);
router.route("/logoff").post(logoff);
router.route("/googleLogon").post(googleLogon);
module.exports=router;
